- name: Install containerd on Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install necessary packages before containerd installation
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gpg
        state: present


    - name: Create keyrings directory
      ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
      args:
        creates: /etc/apt/keyrings


    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: o+r


    - name: Make GPG key readble by anyone
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: a+r


    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu   {{ ansible_distribution_release }} stable"


    - name: Install containerd package from Docker repo
      ansible.builtin.apt:
        pkg:
          - containerd.io
        state: present
        update_cache: true


    - name: Replace a configuration file on /etc/containerd/config.toml
      ansible.builtin.copy:
        src: files/config.toml
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: u+rw,g+r,o+r
      notify: Restart containerd service
