- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true


- name: Install NFS client utility
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    name: nfs-common


# For flannel CNI
- name: Load br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present


- name: Load overlay module
  community.general.modprobe:
    name: overlay
    state: present
    persistent: present
